name: Build Docker
run-name: Build Docker Image and Publish

on:
  push:
    # branches:
    #   - 'master'
    tags:
      - 'v*'

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Comment build info in commit
        uses: actions/github-script@v6
        env:
          STDOUT: "Published new image: `ArtalkJS/Artalk`"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: process.env.STDOUT
            })
