name: Release Build
run-name: Release ${{ inputs.custom || inputs.semver }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        description: Which version you want to increment?
        options:
          - patch
          - minor
          - major
        required: true
      custom:
        description: 'Custom tag. i.e v1.0.0-rc'
        required: false
        default: ''
  # push:
  #   tags:
  #     - v*

env:
  GO_VERSION: '1.19.4'
  DOCKER_IMAGE: ghcr.io/goreleaser/goreleaser-cross
  IMAGE_CACHE_DIR: /tmp/cache/docker-image

jobs:
  tagging:
    name: Tagging new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Git Fetch  
        run: git fetch --prune --unshallow --tags -f

      - name: Get Current Version number
        run: |
          version="$(git describe --tags --abbrev=0)"
          echo "${version}"
          echo "PREV_VERSION=${version}" >> $GITHUB_ENV

      - name: Set node version to 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Get Next Version number
        run: |
          if [ -z "${{ inputs.custom }}" ]; then
            npm install -g semver
            version="v$(semver --increment '${{ inputs.semver }}' '${{ env.PREV_VERSION }}')"
          else
            version="${{ inputs.custom }}"
          fi
          echo "${version}"
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate changelog
        run: make changelog

      - name: Tag and push
        run: |
          if [ ! $(git tag -l "${{ env.VERSION }}") ]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add CHANGELOG.md
            git commit -m "chore: update changelog for ${{ env.VERSION }}"
            git tag '${{ env.VERSION }}'
            git push origin master '${{ env.VERSION }}'
          fi

  build_release:
    name: Build and release
    needs: tagging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      # docker cache
      - name: Docker Image Cache
        id: docker-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.IMAGE_CACHE_DIR }}
          key: docker-image-go-cross-${{ env.GO_VERSION }}

      # pull docker image
      - name: Pull Docker Image
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:v${{ env.GO_VERSION }}
          mkdir -p ${{ env.IMAGE_CACHE_DIR }}
          docker save -o ${{ env.IMAGE_CACHE_DIR }}/go-cross.tar ${{ env.DOCKER_IMAGE }}:v${{ env.GO_VERSION }}

      # restore docker image from cache
      - name: Restore Docker Image from Cache
        if: steps.docker-cache.outputs.cache-hit == 'true'
        run: docker load -i ${{ env.IMAGE_CACHE_DIR }}/go-cross.tar
        
      # pre-build
      - name: Setup Release Environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      # build and release
      - name: Build and Release
        run: make release

